language: python
python:
  - 3.9
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - pipenv install flake8 --dev

script:
  - pipenv run flake8 .
  - pipenv run pytest libpythonpro --cov=cursotools
after_success:
  - pipenv run codecov
